from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='cms-home'),
    path('team/', views.team, name='cms-team'),
    path('project/', views.project, name='cms-project'),
    path('signup/', views.signup, name='cms-signup'),
    path('track/', views.track, name='cms-track'),
    path('ship/', views.ship, name='cms-ship'),
    path('login/', views.login, name='cms-login'),
    path('login-auth/', views.loginauth, name='cms-login-auth'),
    path('acc/', views.acc, name='cms-acc'),
    path('orders/', views.orders, name='cms-orders'),
    path('logout/', views.logout, name='cms-logout'),
    path('updateaddress/', views.updateaddress, name='cms-updateaddress'),
    path('doupdateaddress/', views.doupdateaddress, name='cms-doupdateaddress'),
    path('ship/addship/', views.addship, name='cms-addship'),
    path('updatepass/', views.updatepass, name='cms-updatepass'),
    path('doupdatepass/', views.doupdatepass, name='cms-doupdatepass'),
    path('track/showtrack/', views.showtrack, name='cms-showtrack'),
    path('god/', views.god, name='cms-god'),
    path('delacc/', views.delacc, name='cms-delacc'),
    path('godviewsorders/', views.vieworders, name='cms-vieworders'),
    path('godviewspunypeople/', views.viewusers, name='cms-viewusers'),
    path('yourdead/', views.delusers, name='cms-delusers'),
    path('delete/', views.delete, name='cms-delete'),
    path('updatestatus/', views.updatestatus, name='cms-updatestatus'),
    path('doupdatestatus/', views.doupdatestatus, name='cms-doupdatestatus'),
]